// Code generated by "stringer -type=DeleteUserCommandType"; DO NOT EDIT.

package delete_user

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeleteGuestProfile-0]
	_ = x[DeleteHostProfile-1]
	_ = x[RollbackGuestProfile-2]
	_ = x[RollbackHostProfile-3]
	_ = x[DeleteGuestAccountCredentials-4]
	_ = x[DeleteHostAccountCredentials-5]
	_ = x[RollbackGuestAccountCredentials-6]
	_ = x[RollbackHostAccountCredentials-7]
	_ = x[DeleteHostAccommodations-8]
	_ = x[RollbackHostAccommodations-9]
	_ = x[DeleteHostReservations-10]
	_ = x[DeleteHostNotifications-11]
	_ = x[DeleteGuestNotifications-12]
	_ = x[RollbackHostNotifications-13]
	_ = x[RollbackGuestNotifications-14]
	_ = x[FinishDeletion-15]
	_ = x[UnknownCommand-16]
}

const _DeleteUserCommandType_name = "DeleteGuestProfileDeleteHostProfileRollbackGuestProfileRollbackHostProfileDeleteGuestAccountCredentialsDeleteHostAccountCredentialsRollbackGuestAccountCredentialsRollbackHostAccountCredentialsDeleteHostAccommodationsRollbackHostAccommodationsDeleteHostReservationsDeleteHostNotificationsDeleteGuestNotificationsRollbackHostNotificationsRollbackGuestNotificationsFinishDeletionUnknownCommand"

var _DeleteUserCommandType_index = [...]uint16{0, 18, 35, 55, 74, 103, 131, 162, 192, 216, 242, 264, 287, 311, 336, 362, 376, 390}

func (i DeleteUserCommandType) String() string {
	if i < 0 || i >= DeleteUserCommandType(len(_DeleteUserCommandType_index)-1) {
		return "DeleteUserCommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeleteUserCommandType_name[_DeleteUserCommandType_index[i]:_DeleteUserCommandType_index[i+1]]
}
