version: '3.1'
services:

  mongo:
    image: mongo
    restart: always
    container_name: flights-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
    - flightsAppDB:/data/db
    ports:
    - 5000:27017
    networks:
      - network

  mongo-seed:
    image: mongo-seed
    container_name: mongo-seed
    build:
      context: ./FlightBookingApp/MongoSeed
      dockerfile: Dockerfile
    depends_on:
    - mongo
    networks:
      - network

volumes:
  flightsAppDB: null

networks:
  network:
    external: true
    driver: bridge
