definitions:
  dto.CreatedResponse:
    properties:
      id:
        type: string
    type: object
  dto.SimpleResponse:
    properties:
      message:
        type: string
    type: object
  model.Address:
    properties:
      city:
        type: string
      country:
        type: string
      street:
        type: string
      streetNumber:
        type: string
    required:
    - city
    - country
    - street
    - streetNumber
    type: object
  model.Airport:
    properties:
      address:
        $ref: '#/definitions/model.Address'
      id:
        type: string
      name:
        type: string
    required:
    - address
    - name
    type: object
  model.Flight:
    properties:
      canceled:
        type: boolean
      departureDateTime:
        description: TODO namestiti da smesta UTC
        type: string
      destination:
        $ref: '#/definitions/model.Airport'
      id:
        type: string
      numberOfSeats:
        minimum: 0
        type: integer
      price:
        minimum: 0
        type: number
      startPoint:
        $ref: '#/definitions/model.Airport'
      vacantSeats:
        type: integer
    required:
    - departureDateTime
    - destination
    - numberOfSeats
    - price
    - startPoint
    type: object
  model.Ticket:
    properties:
      buyer:
        type: string
      flightId:
        type: string
      id:
        type: string
      owner:
        type: string
    required:
    - buyer
    - flightId
    - owner
    type: object
  utils.Page:
    properties:
      data: {}
      entityCount:
        type: integer
    type: object
info:
  contact: {}
paths:
  /airport:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Airport'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Airport
  /airport/{id}:
    get:
      parameters:
      - description: Airport ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Airport'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Airport
  /flight:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Flight'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Flight
    post:
      parameters:
      - description: Flight
        in: body
        name: flight
        required: true
        schema:
          $ref: '#/definitions/model.Flight'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreatedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Flight
  /flight/{id}:
    get:
      parameters:
      - description: Flight ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Flight'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Flight
    patch:
      parameters:
      - description: Flight ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Flight
  /flight/search:
    get:
      parameters:
      - description: Departure date, must be in this format YYYY-MM-DD
        format: yyyy-mm-dd
        in: query
        name: departureDate
        required: true
        type: string
      - description: Destination country
        in: query
        name: destinationCountry
        required: true
        type: string
      - description: Destination city
        in: query
        name: destinationCity
        required: true
        type: string
      - description: Starting point country
        in: query
        name: startPointCountry
        required: true
        type: string
      - description: Starting point  city
        in: query
        name: startPointCity
        required: true
        type: string
      - description: Desired number of seats
        in: query
        name: desiredNumberOfSeats
        required: true
        type: integer
      - description: Page number
        in: query
        name: pageNumber
        required: true
        type: integer
      - description: Results per page
        in: query
        name: resultsPerPage
        required: true
        type: integer
      - description: Sort direction (asc, dsc, no_sort)
        in: query
        name: sortDirection
        required: true
        type: string
      - description: Sort type, it can be departureDateTime or price
        in: query
        name: sortType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/utils.Page'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Flight
  /ticket:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Ticket'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Ticket
    post:
      parameters:
      - description: Ticket
        in: body
        name: ticket
        required: true
        schema:
          $ref: '#/definitions/model.Ticket'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreatedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Ticket
  /ticket/{id}:
    delete:
      parameters:
      - description: Ticket ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Ticket
    get:
      parameters:
      - description: Ticket ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Ticket'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.SimpleResponse'
      tags:
      - Ticket
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
