package model

type ServiceRole int8

const (
	ROLE_ACCOMMODATION_SERVICE ServiceRole = iota
	ROLE_API_GATEWAY
	ROLE_AUTHORIZATION_SERVICE
	ROLE_NOTIFICATION_SERVICE
	ROLE_RATING_SERVICE
	ROLE_RESERVATION_SERVICE
	ROLE_USER_PROFILE_SERVICE
	ROLE_UNKNOWN
)
