version: "3.1"

services:
  flights-app:
    image: flights-app
    build:
        context: FlightBookingApp
        dockerfile: Dockerfile
    restart: always
    container_name: "flights-app"
    ports:
      - 4200:4200
    environment:
      - PORT=4200

